#include "coderenderparm.h"

// Generated from the 617 code-render-parm constructors recovered with PDB
// names and initializer strings.  Registration is deliberately lazy so image
// and render-program resources are not touched during CRT static startup.

namespace {
	struct recoveredCodeParmDef_t {
		const char * name;
		const char * initializer;
	};

	const recoveredCodeParmDef_t recoveredCodeParmDefs[] = {
		{ "pageTableMap", "Tex\t_vmtrPageTable" },
		{ "vmtrPageTableMap", "Tex\t_vmtrPageTable" },
		{ "physicalVmtrPagesMap0", "Tex\t_physicalVmtrPages0" },
		{ "physicalVmtrPagesMap1", "Tex\t_physicalVmtrPages1" },
		{ "physicalVmtrPagesMap2", "Tex\t_physicalVmtrPages2" },
		{ "physicalUniquePagesMap0", "Tex\t_physicalUniquePages0" },
		{ "physicalUniquePagesMap1", "Tex\t_physicalUniquePages1" },
		{ "physicalUniquePagesMap2", "Tex\t_physicalUniquePages2" },
		{ "physicalUniqueDiffuseOnlyPagesMap0", "Tex\t_physicalUniqueDiffuseOnlyPages0" },
		{ "physicalUniqueDiffuseOnlyPagesMap1", "Tex\t_physicalUniqueDiffuseOnlyPages1" },
		{ "physicalUniqueDiffuseOnlyPagesMap2", "Tex\t_physicalUniqueDiffuseOnlyPages2" },
		{ "physicalUniqueDiffuseOnly2PagesMap0", "Tex\t_physicalUniqueDiffuseOnly2Pages0" },
		{ "physicalUniqueDiffuseOnly2PagesMap1", "Tex\t_physicalUniqueDiffuseOnly2Pages1" },
		{ "physicalUniqueDiffuseOnly2PagesMap2", "Tex\t_physicalUniqueDiffuseOnly2Pages2" },
		{ "physicalVmtrMappingsMap0", "Tex\t_physicalVmtrMappings0" },
		{ "physicalVmtrMappingsMap1", "Tex\t_physicalVmtrMappings1" },
		{ "physicalVmtrMappingsMap2", "Tex\t_physicalVmtrMappings2" },
		{ "physicalUniqueMappingsMap0", "Tex\t_physicalUniqueMappings0" },
		{ "physicalUniqueMappingsMap1", "Tex\t_physicalUniqueMappings1" },
		{ "physicalUniqueMappingsMap2", "Tex\t_physicalUniqueMappings2" },
		{ "physicalUniqueDiffuseOnlyMappingsMap0", "Tex\t_physicalUniqueDiffuseOnlyMappings0" },
		{ "physicalUniqueDiffuseOnlyMappingsMap1", "Tex\t_physicalUniqueDiffuseOnlyMappings1" },
		{ "physicalUniqueDiffuseOnlyMappingsMap2", "Tex\t_physicalUniqueDiffuseOnlyMappings2" },
		{ "physicalUniqueDiffuseOnly2MappingsMap0", "Tex\t_physicalUniqueDiffuseOnly2Mappings0" },
		{ "physicalUniqueDiffuseOnly2MappingsMap1", "Tex\t_physicalUniqueDiffuseOnly2Mappings1" },
		{ "physicalUniqueDiffuseOnly2MappingsMap2", "Tex\t_physicalUniqueDiffuseOnly2Mappings2" },
		{ "physicalVmtrFilterParms", "Vec\t0" },
		{ "physicalUniqueFilterParms", "Vec\t0" },
		{ "physicalUniqueDiffuseOnlyFilterParms", "Vec\t0" },
		{ "physicalUniqueDiffuseOnly2FilterParms", "Vec\t0" },
		{ "virtualTextureFeedbackFloat", "Vec\t0" },
		{ "dynamicEnvMap", "TexCube\t_environment" },
		{ "hqSpecularNormal", "Vec 0 bool" },
		{ "testEnvLOD", "Vec 0 range 0, 3" },
		{ "testImageLOD", "Vec 0" },
		{ "testImageFlip", "Vec   {1, 1, 1, 1}" },
		{ "envMap", "TexCube\tenv/senetest_px" },
		{ "envBlendTime", "Vec 2.2" },
		{ "cbConversionLUT", "Tex\t_colorBalanceLUT" },
		{ "cbMidTone", "Vec\t{0, 0, 0, 1} range -100.0, 100.0" },
		{ "cbHighlight", "Vec\t{0, 0, 0, 1} range -100.0, 100.0" },
		{ "cbShadow", "Vec\t{0, 0, 0, 1} range -100.0, 100.0" },
		{ "cbDesaturate", "Vec\t{0.0} range 0.0, 1.0" },
		{ "cbBrightness", "Vec 1 range 0.4, 1.8" },
		{ "cbColorDodge", "Vec 0 range 0.0, 1.0" },
		{ "cbColorBurn", "Vec 1 range 0.0, 1.0" },
		{ "cbColorMultiply", "Vec 1 range 0.0, 1.0" },
		{ "cbColorScreen", "Vec 0 range 0.0, 1.0" },
		{ "cbBlackLevel", "Vec 0 range -1.0, 1.0" },
		{ "screenOverlay", "Tex _default" },
		{ "overlayOpacity", "Vec 0 range 0.0, 1.0" },
		{ "showOverlay", "Vec 1 bool" },
		{ "bumpMap", "String\tconstantColor(0.5,0.5,1,0)" },
		{ "diffuseMap", "String\tconstantColor(0,0,0,0)" },
		{ "specularMap", "String\tconstantColor(0,0,0,0)" },
		{ "powerMap", "String\tconstantColor(1,1,1,1)" },
		{ "coverMap", "String\tconstantColor(1,1,1,1)" },
		{ "virtualTransMap", "String\tconstantColor(1,1,1,1)" },
		{ "megaTextureAddMap", "String\t" },
		{ "transSortMap", "String\tconstantColor(0,0,0,0)" },
		{ "transAtlasMap", "String\tconstantColor(0,0,0,0)" },
		{ "transSortAtlasDim", "Vec {4096.0 , 4096.0, 0.000244140625, 0.000244140625}" },
		{ "transAtlasScaleBias", "Vec {1.0, 1.0, 0.0, 0.0}" },
		{ "transAtlasScaleBiasInv", "Vec {1.0, 1.0, 0.0, 0.0}" },
		{ "cpuMap", "String\tconstantColor(0,0,0,0)" },
		{ "textureMap", "Tex\t_default" },
		{ "heightMap", "Tex\t_black" },
		{ "transMap", "Tex\t_black" },
		{ "transMap1", "Tex\t_black" },
		{ "transMap2", "Tex\t_black" },
		{ "fadeMap", "Tex\t_black" },
		{ "spare1Map", "Tex\t_default" },
		{ "spare2Map", "Tex\t_default" },
		{ "spare3Map", "Tex\t_default" },
		{ "spareBumpMap", "Tex\tconstantColor(0.5,0.5,1.0,0.0)" },
		{ "spareBumpMap2", "Tex\tconstantColor(0.5,0.5,1.0,0.0)" },
		{ "spareCube1Map", "TexCube\t_defaultCube" },
		{ "spareSpecularMap", "Tex\tconstantColor(0,0,0,0)" },
		{ "spareSpecularMap2", "Tex\tconstantColor(0,0,0,0)" },
		{ "testMap", "Tex\ttextures/bigchars.tga" },
		{ "testMap2", "Tex\ttextures/bigchars.tga" },
		{ "qer_editorImage", "String\t" },
		{ "editorAlpha", "Vec\t1.0" },
		{ "editorDraw", "Vec   0 bool" },
		{ "virtualPageProgram", "Program\t0" },
		{ "shadowProgram", "Program\t0" },
		{ "stageProgram", "Program\t0" },
		{ "interactionProgram", "Program\t0" },
		{ "depthFillProgram", "Program\t0" },
		{ "ambientProgram", "Program\t0" },
		{ "addProgram", "Program\t0" },
		{ "blendProgram", "Program\t0" },
		{ "fadePerturbProgram", "Program\t0" },
		{ "renderBump", "String\t" },
		{ "ifparm", "Vec\t1" },
		{ "time", "Vec\t0" },
		{ "sMatrix", "Vec\t{1, 0, 0, 0}" },
		{ "tMatrix", "Vec\t{0, 1, 0, 0}" },
		{ "rMatrix", "Vec\t{0, 0, 1, 0}" },
		{ "qMatrix", "Vec\t{0, 0, 0, 1}" },
		{ "sMatrix1", "Vec\t{1, 0, 0, 0}" },
		{ "tMatrix1", "Vec\t{0, 1, 0, 0}" },
		{ "rMatrix1", "Vec\t{0, 0, 1, 0}" },
		{ "qMatrix1", "Vec\t{0, 0, 0, 1}" },
		{ "select", "Vec\t{1, 0}" },
		{ "color", "Vec\t{1, 1, 1, 1} color" },
		{ "coverage", "Vec\t1" },
		{ "modelFade", "Vec\t1" },
		{ "rotate", "Vec\t0" },
		{ "scroll", "Vec\t0" },
		{ "timeScale", "Vec\t1 range 0, 10" },
		{ "timePhase", "Vec\t0 range 0, 1" },
		{ "timeOffset", "Vec\t0" },
		{ "timeStop", "Vec\t0" },
		{ "diversity", "Vec\t0" },
		{ "wind", "Vec\t{0, 1, 0, 0}" },
		{ "particleScale", "Vec\t{1, 1, 1, 1}" },
		{ "particleDistScale", "Vec {1, 1, 1, 1}" },
		{ "particleVel", "Vec\t0" },
		{ "particleLOD", "Vec\t0" },
		{ "screenSizeRatio", "Vec 1.7778" },
		{ "waveBase", "Vec   0" },
		{ "waveAmp", "Vec   1" },
		{ "wavePhase", "Vec   0" },
		{ "waveFreq", "Vec   1" },
		{ "waveSpread", "Vec   1" },
		{ "temp1", "Vec\t0" },
		{ "temp2", "Vec\t0" },
		{ "temp3", "Vec\t0" },
		{ "temp4", "Vec\t0" },
		{ "temp5", "Vec\t0" },
		{ "temp6", "Vec\t0" },
		{ "temp7", "Vec\t0" },
		{ "temp8", "Vec\t0" },
		{ "temp9", "Vec\t0" },
		{ "temp10", "Vec\t0" },
		{ "temp11", "Vec\t0" },
		{ "temp12", "Vec\t0" },
		{ "temp13", "Vec\t0" },
		{ "temp14", "Vec\t0" },
		{ "temp15", "Vec\t0" },
		{ "temp16", "Vec\t0" },
		{ "temp17", "Vec\t0" },
		{ "temp18", "Vec\t0" },
		{ "temp19", "Vec\t0" },
		{ "temp20", "Vec\t0" },
		{ "temp21", "Vec\t0" },
		{ "temp22", "Vec\t0" },
		{ "temp23", "Vec\t0" },
		{ "temp24", "Vec\t0" },
		{ "temp25", "Vec\t0" },
		{ "temp26", "Vec\t0" },
		{ "temp27", "Vec\t0" },
		{ "temp28", "Vec\t0" },
		{ "temp29", "Vec\t0" },
		{ "temp30", "Vec\t0" },
		{ "temp31", "Vec\t0" },
		{ "temp32", "Vec\t0" },
		{ "tempCos", "Vec 0" },
		{ "tempSin", "Vec 0" },
		{ "tempCosNeg", "Vec 0" },
		{ "tempSinNeg", "Vec 0" },
		{ "surfaceFlags", "Vec\t0" },
		{ "contentFlags", "Vec\t1" },
		{ "surfaceType", "Vec\t0" },
		{ "toolsFlags", "Vec\t0" },
		{ "discrete", "Vec\t0 bool" },
		{ "noFragment", "Vec\t0 bool" },
		{ "forceOpaque", "Vec\t0" },
		{ "allowOverlays", "Vec\t1 bool" },
		{ "noShadows", "Vec\t0 bool" },
		{ "noSelfShadow", "Vec\t0 bool" },
		{ "isDrawn", "Vec\t1" },
		{ "skipSurfaceInfo", "Vec\t0 bool" },
		{ "autoSpriteType", "Vec\t0" },
		{ "decalProjType", "Vec\t0" },
		{ "polygonOffset", "Vec\t0" },
		{ "vertexColor", "Vec {0, 1}" },
		{ "lightRotation", "Vec 0" },
		{ "lightTranslation", "Vec 0" },
		{ "lightScale", "Vec 1" },
		{ "lightOscillationAmp", "Vec 1" },
		{ "lightOscillationPhase", "Vec 0" },
		{ "lightOscillationFreq", "Vec 0" },
		{ "lightProjectionS", "Vec 0" },
		{ "lightProjectionT", "Vec 0" },
		{ "lightProjectionR", "Vec 0" },
		{ "lightProjectionQ", "Vec 0" },
		{ "staticSpecularVector", "Vec {0, 0.7, 0.7}" },
		{ "staticSpecularScale", "Vec 10" },
		{ "localViewOrigin", "Vec 0" },
		{ "localViewLeft", "Vec 0" },
		{ "localViewUp", "Vec 0" },
		{ "localLightOrigin", "Vec 0" },
		{ "globalViewOrigin", "Vec 1" },
		{ "globalViewLeft", "Vec 0" },
		{ "globalViewFwd", "Vec 0" },
		{ "globalViewUp", "Vec 0" },
		{ "globalLightOrigin", "Vec 0" },
		{ "frameNumber", "Vec\t0" },
		{ "viewRandom", "Vec\t0" },
		{ "positionToViewSpace", "Vec\t0" },
		{ "positionToViewTexture", "Vec\t0" },
		{ "positionToViewTexture2", "Vec\t0" },
		{ "positionToFeedback", "Vec\t0" },
		{ "renderPositionToViewTexture", "Vec\t0" },
		{ "renderPositionToViewTexture2", "Vec\t0" },
		{ "viewMatrixX", "Vec 0" },
		{ "viewMatrixY", "Vec 0" },
		{ "viewMatrixZ", "Vec 0" },
		{ "viewMatrixW", "Vec 0" },
		{ "inverseViewMatrixX", "Vec 0" },
		{ "inverseViewMatrixY", "Vec 0" },
		{ "inverseViewMatrixZ", "Vec 0" },
		{ "inverseViewMatrixW", "Vec 0" },
		{ "modelMatrixX", "Vec {1, 0, 0, 0}" },
		{ "modelMatrixY", "Vec {0, 1, 0, 0}" },
		{ "modelMatrixZ", "Vec {0, 0, 1, 0}" },
		{ "modelMatrixW", "Vec {0, 0, 0, 1}" },
		{ "inverseModelMatrixX", "Vec {1, 0, 0, 0}" },
		{ "inverseModelMatrixY", "Vec {0, 1, 0, 0}" },
		{ "inverseModelMatrixZ", "Vec {0, 0, 1, 0}" },
		{ "inverseModelMatrixW", "Vec {0, 0, 0, 1}" },
		{ "projectionMatrixX", "Vec 0" },
		{ "projectionMatrixY", "Vec 0" },
		{ "projectionMatrixZ", "Vec 0" },
		{ "projectionMatrixW", "Vec 0" },
		{ "inverseProjectionMatrixX", "Vec 0" },
		{ "inverseProjectionMatrixY", "Vec 0" },
		{ "inverseProjectionMatrixZ", "Vec 0" },
		{ "inverseProjectionMatrixW", "Vec 0" },
		{ "mvpMatrixX", "Vec 0" },
		{ "mvpMatrixY", "Vec 0" },
		{ "mvpMatrixZ", "Vec 0" },
		{ "mvpMatrixW", "Vec 0" },
		{ "inverseMVPMatrixX", "Vec 0" },
		{ "inverseMVPMatrixY", "Vec 0" },
		{ "inverseMVPMatrixZ", "Vec 0" },
		{ "inverseMVPMatrixW", "Vec 0" },
		{ "newDiffuseScale", "Vec\t{1, 1, 1}" },
		{ "newSpecularScale", "Vec\t{1, 1, 1}" },
		{ "newPowerScale", "Vec\t0" },
		{ "newAmbientScale", "Vec\t0.3" },
		{ "surfaceRadiosityScale", "Vec\t1" },
		{ "activeRadiosityScale", "Vec\t1" },
		{ "sharpBakedAmbient", "Vec\t0 bool" },
		{ "diffuseScale", "Vec 2 color 0, 4" },
		{ "specularScale", "Vec 0.5 color 0, 8" },
		{ "alphaScale", "Vec 64 range 1.0, 100.0" },
		{ "powerMip", "Vec 1 range 0, 5" },
		{ "fadeScale", "Vec 1 color" },
		{ "envScale", "Vec 1 color" },
		{ "envGrazingScale", "Vec 1 color" },
		{ "envOrigin", "Vec 0" },
		{ "envSize", "Vec 30000" },
		{ "viewGraze", "Vec\t0.0 range 0, 1" },
		{ "grazingDiffuseColor", "Vec\t0.0 range 0, 1" },
		{ "grazingSpecularColor", "Vec\t0.0 range 0, 1" },
		{ "anisotropy", "Vec\t1.0 range 0, 1" },
		{ "lightProjectMap", "Tex\tlights/squarelight1.tga" },
		{ "lightFalloffMap", "Tex\tlights/squareLight1.tga" },
		{ "lightColor", "Vec\t{1, 1, 1}" },
		{ "viewDepthMap", "Tex\t_viewDepth" },
		{ "viewColorMap", "Tex\t_viewColor0" },
		{ "dither16Map", "Tex\t_dither16" },
		{ "dither256Map", "Tex\t_dither256" },
		{ "loadingIcon", "Tex   hqcompress textures/guis/loading_icon" },
		{ "lightDepthMap", "Tex2D\t\t\t_shadowBuffer_d" },
		{ "lightDepthCompareMap", "TexShadow2D\t_shadowBuffer_d" },
		{ "lightDepthVarianceMap", "Tex2D\t\t\t_varianceShadowMap" },
		{ "shadowJitterMap", "Tex\t\t\t_jitter1" },
		{ "jitter1Map", "Tex\t\t\t_jitter1" },
		{ "jitter4Map", "Tex\t\t\t_jitter4" },
		{ "jitter16Map", "Tex\t\t\t_jitter16" },
		{ "shadowFactor2Map", "Tex\t\t\t_shadowFactor2" },
		{ "shadowFactor3Map", "Tex\t\t\t_shadowFactor3" },
		{ "shadowFactor4Map", "Tex\t\t\t_shadowFactor4" },
		{ "shadowBufferResolution", "Vec\t{2048, 0.00048828125, -0.00048828125, 0}" },
		{ "shadowFade", "Vec\t{1, 0, 0, 0}" },
		{ "lightFade", "Vec\t1" },
		{ "localToLightS", "Vec\t0" },
		{ "localToLightT", "Vec\t0" },
		{ "localToLightR", "Vec\t0" },
		{ "localToLightQ", "Vec\t0" },
		{ "exposure", "Vec 1" },
		{ "screenScale", "Vec 1" },
		{ "glarePreScale", "Vec 1" },
		{ "skyGlarePreScale", "Vec 1" },
		{ "glareScale", "Vec 0.3" },
		{ "glareStart", "Vec 0.8" },
		{ "glareStep", "Vec 1" },
		{ "glareMax", "Vec 10" },
		{ "glareMap", "Tex\t_screenMip3" },
		{ "glareScreenBias", "Vec 0.5" },
		{ "depthOfField", "Vec {1.0, 1.0, 5500.0, 1.0}" },
		{ "globalBlur", "Vec 0" },
		{ "doubleVision", "Vec 0" },
		{ "depthBasedColorGrading", "Vec 0 bool" },
		{ "userEnvMap", "Environment env/default_px" },
		{ "ambientEnvMap", "Environment env/ambiTest_px" },
		{ "postDistortionMap", "Tex _black" },
		{ "bakedViewOrigin", "Vec\t0" },
		{ "virtualMapping", "Vec 0" },
		{ "useVirtualMapping", "Vec 0" },
		{ "useSkinBlending", "Vec 0" },
		{ "textureJitterScale", "Vec 1" },
		{ "fogScale", "Vec 0.00005 range 0, 0.0002" },
		{ "fogColor", "Vec {0.2, 0.43, 0.5}" },
		{ "fogStart", "Vec 0" },
		{ "fogEnd", "Vec 300000 range 0, 300000" },
		{ "materialCoverage", "Vec\t0" },
		{ "coverageBad", "Vec\t0" },
		{ "coverageInvisible", "Vec\t1" },
		{ "coveragePerforated", "Vec\t2" },
		{ "coverageTranslucent", "Vec\t3" },
		{ "coverageOpaque", "Vec\t4" },
		{ "stageSort", "Vec\t0" },
		{ "sortEmit", "Vec\t10" },
		{ "sortEmitOnly", "Vec\t85" },
		{ "sortCoverage", "Vec\t100" },
		{ "sortSkybox", "Vec\t140" },
		{ "sortLight", "Vec\t300" },
		{ "sortDecal", "Vec\t400" },
		{ "sortTransSort", "Vec 495" },
		{ "sortTrans", "Vec\t500" },
		{ "sortWater", "Vec\t650" },
		{ "sortParticleTest", "Vec\t1100" },
		{ "sortScreenEffect", "Vec\t1150" },
		{ "sortPerturber", "Vec\t1200" },
		{ "surf_NoDamage", "Vec   $evalint( 1 << 4 ) " },
		{ "surf_Slick", "Vec\t$evalint( 1 << 5 ) " },
		{ "surf_Collision", "Vec\t$evalint( 1 << 6 ) " },
		{ "surf_Ladder", "Vec\t$evalint( 1 << 7 ) " },
		{ "surf_NoImpact", "Vec\t$evalint( 1 << 8 ) " },
		{ "surf_NoSteps", "Vec\t$evalint( 1 << 9 ) " },
		{ "surf_Stairs", "Vec\t$evalint( 1 << 10 )" },
		{ "surf_OcclusionTest", "Vec\t$evalint( 1 << 11 )" },
		{ "surf_ShadowCaster", "Vec\t$evalint( 1 << 12 )" },
		{ "surf_NullNormal", "Vec\t$evalint( 1 << 13 )" },
		{ "surf_NoAreas", "Vec\t$evalint( 1 << 14 )" },
		{ "surf_non_penetrable", "Vec\t$evalint( 1 << 15 )" },
		{ "surf_NoShoot", "Vec\t$evalint( 1 << 16 )" },
		{ "surfType_None", "Vec\t0" },
		{ "surfType_Metal", "Vec\t1" },
		{ "surfType_Stone", "Vec\t2" },
		{ "surfType_Flesh", "Vec\t3" },
		{ "surfType_Wood", "Vec\t4" },
		{ "surfType_Cardboard", "Vec\t5" },
		{ "surfType_Liquid", "Vec\t6" },
		{ "surfType_Glass", "Vec\t7" },
		{ "surfType_Plastic", "Vec\t8" },
		{ "surfType_Asphalt", "Vec\t9" },
		{ "surfType_Dirt", "Vec\t10" },
		{ "surfType_Concrete", "Vec\t11" },
		{ "surfType_Foliage", "Vec\t12" },
		{ "surfType_Linoleum", "Vec\t13" },
		{ "surfType_Fabric", "Vec\t14" },
		{ "surfType_Rubber", "Vec\t15" },
		{ "surfType_Rock", "Vec\t16" },
		{ "surfType_SteamPipe", "Vec\t17" },
		{ "surfType_WaterPipe", "Vec\t18" },
		{ "surfType_Armor", "Vec\t19" },
		{ "surfType_Sludge", "Vec\t20" },
		{ "surfType_ImpNest", "Vec\t21" },
		{ "surfType_HollowMetal", "Vec\t22" },
		{ "surfType_FleshPlayer", "Vec\t23" },
		{ "surfType_FleshDarkAngel", "Vec 25" },
		{ "surfType_BloodPool", "Vec 26" },
		{ "surfType_Ash", "Vec 28" },
		{ "surfType_FleshMutant", "Vec 29" },
		{ "surfType_ThickPadding", "Vec 30" },
		{ "surfType_PlayerAPCMetal", "Vec 31" },
		{ "surfType_RicketyMetal", "Vec 32" },
		{ "surfType_RicketyWood", "Vec 33" },
		{ "contents_NonSolid", "Vec 0" },
		{ "contents_Solid", "Vec $evalint( 1 << 0 )" },
		{ "contents_Opaque", "Vec $evalint( 1 << 1 )" },
		{ "contents_Water", "Vec $evalint( 1 << 2 )" },
		{ "contents_PlayerClip", "Vec $evalint( 1 << 3 )" },
		{ "contents_MonsterClip", "Vec $evalint( 1 << 4 )" },
		{ "contents_VehicleClip", "Vec $evalint( 1 << 5 )" },
		{ "contents_MoveableClip", "Vec $evalint( 1 << 6 )" },
		{ "contents_ShotClip", "Vec $evalint( 1 << 7 )" },
		{ "contents_IKClip", "Vec $evalint( 1 << 8 )" },
		{ "contents_AIAware", "Vec $evalint( 1 << 9 )" },
		{ "contents_AI", "Vec $evalint( 1 << 10 )" },
		{ "contents_Projectile", "Vec $evalint( 1 << 11 )" },
		{ "contents_Corpse", "Vec $evalint( 1 << 12 )" },
		{ "contents_Breakable", "Vec $evalint( 1 << 13 )" },
		{ "contents_Trigger", "Vec $evalint( 1 << 14 )" },
		{ "contents_Player", "Vec $evalint( 1 << 15 )" },
		{ "contents_Vehicle", "Vec $evalint( 1 << 16 )" },
		{ "contents_Obstacle", "Vec $evalint( 1 << 17 )" },
		{ "contents_PlayerCoverClip", "Vec $evalint( 1 << 19 )" },
		{ "contents_MonsterCoverClip", "Vec $evalint( 1 << 20 )" },
		{ "contents_PlayerFocus", "Vec $evalint( 1 << 21 )" },
		{ "contents_AASSolid", "Vec $evalint( 1 << 26 )" },
		{ "contents_AASObstacle", "Vec $evalint( 1 << 27 )" },
		{ "contents_AASClusterPortal", "Vec $evalint( 1 << 28 )" },
		{ "contents_AASWalkableWall", "Vec $evalint( 1 << 29 )" },
		{ "contents_NoCover", "Vec $evalint( 1 << 30 )" },
		{ "toolsflag_NoCSG", "Vec $evalint( 1 << 0 )" },
		{ "toolsflag_SoundClip", "Vec $evalint( 1 << 1 )" },
		{ "toolsflag_SoundClipTrans", "Vec $evalint( 1 << 2 )" },
		{ "toolsflag_SoundDoor", "Vec $evalint( 1 << 3 )" },
		{ "toolsflag_SoundPortal", "Vec $evalint( 1 << 4 )" },
		{ "toolsflag_PVSClip", "Vec $evalint( 1 << 5 )" },
		{ "toolsflag_SoundTrigger", "Vec $evalint( 1 << 6 )" },
		{ "toolsflag_ManifoldHint", "Vec $evalint( 1 << 7 )" },
		{ "ambientLightColor", "Vec 1" },
		{ "parallelShadowS", "Vec\t0" },
		{ "parallelShadowT", "Vec\t0" },
		{ "parallelShadowR", "Vec\t0" },
		{ "parallelShadowQ", "Vec\t0" },
		{ "landIndexMapSize", "Vec {32, 32, $evalfloat( 1 / 32 ), $evalfloat( 1 / 32 )} " },
		{ "godRaysEnable", "Vec 0 bool" },
		{ "godRaysDirection", "Vec\t{0, 0, 1}" },
		{ "godRaysSourceTexture", "Tex   hqcompress textures/sfx/sunray.tga" },
		{ "godRaysSize", "Vec 768" },
		{ "godRaysSourceSize", "vec 256" },
		{ "normalRotate", "Vec\t0" },
		{ "stampHighlight", "Vec\t0" },
		{ "binkY", "Tex\t_default" },
		{ "binkCr", "Tex\t_default" },
		{ "binkCb", "Tex\t_default" },
		{ "windowPosToProjectedTexS", "Vec\t0" },
		{ "windowPosToProjectedTexT", "Vec\t0" },
		{ "windowPosToProjectedTexR", "Vec\t0" },
		{ "windowPosToProjectedTexQ", "Vec\t0" },
		{ "decalPos", "Vec { 0 }" },
		{ "decalPosToLocalBoxSpaceX", "Vec\t0" },
		{ "decalPosToLocalBoxSpaceY", "Vec\t0" },
		{ "decalPosToLocalBoxSpaceZ", "Vec\t0" },
		{ "decalPosToLocalBoxSpaceW", "Vec\t0" },
		{ "windowPosToDimShadowBlurS", "Vec\t0" },
		{ "windowPosToDimShadowBlurT", "Vec\t0" },
		{ "windowPosToDimShadowBlurR", "Vec\t0" },
		{ "windowPosToDimShadowBlurQ", "Vec\t0" },
		{ "dimShadowDepthMap", "TexShadow2D _dimShadow_d" },
		{ "dimShadowExtrude", "Vec\t0" },
		{ "dimShadowClipPlane", "Vec\t0" },
		{ "dimShadowFade", "Vec\t1" },
		{ "editorColor", "Vec 0.5 color" },
		{ "editorMap", "Tex _default" },
		{ "editorFlatShaded", "Vec 0" },
		{ "corneaPowLevel", "Vec 200" },
		{ "irisPowLevel", "Vec 100" },
		{ "eyeHighlightPowLevel", "Vec 60" },
		{ "eyeAmbScale", "Vec 0.3" },
		{ "showEyeDebug", "Vec 0" },
		{ "floatingStampVmtr", "Vec 0" },
		{ "floatingStampSelect", "Vec { 0, 1 }" },
		{ "floatingStampSMatrix", "Vec\t{ 1, 0, 0, 0 }" },
		{ "floatingStampTMatrix", "Vec\t{ 0, 1, 0, 0 }" },
		{ "floatingStampRMatrix", "Vec\t{ 0, 0, 1, 0 }" },
		{ "floatingStampQMatrix", "Vec\t{ 0, 0, 0, 1 }" },
		{ "floatingStampFullBright", "Vec 0" },
		{ "fontThreshold", "Vec 0.5" },
		{ "fontSmooth", "Vec 0.1" },
		{ "fontOutline", "Vec 0.4" },
		{ "godRayQuadScaleBias", "Vec { 1.0, 1.0, 0.0, 0.0 }" },
		{ "godRaySourceScaleBias", "Vec { 1.0, 1.0, 0.0, 0.0 }" },
		{ "guiBlackLevel", "Vec 0 range -1.0, 1.0" },
		{ "secondaryLightDir", "Vec 0" },
		{ "secondaryLightColor", "Vec 0" },
		{ "ambientLerp", "Vec { 1, 0.5, 24, 0 }" },
		{ "directLerp", "Vec { 0, 1, 24, 0 }" },
		{ "landRadiosityScale", "Vec\t1" },
		{ "radShowBackFaces", "Vec\t0" },
		{ "landSunDirection", "Vec\t{ -1, 0, 0.5 }" },
		{ "landSunColor", "Vec\t{ 1, 1, 1 }" },
		{ "landAmbientColor", "Vec\t{ 0.1, 0.1, 0.1 }" },
		{ "landIndexColor", "Vec\t{ 1, 1, 1, 0 }" },
		{ "stampCovers", "Vec\t{ 1, 1, 1, 0 }" },
		{ "stampScales", "Vec\t{ 1, 1, 1, 0 }" },
		{ "stampNormal", "Vec\t{ 0, 0, 1 }" },
		{ "landIndexMap", "Tex\t_black" },
		{ "landVmtrMap", "Tex\t_black" },
		{ "landIndexFeedbackFloat", "Vec\t0" },
		{ "vmtrDimensions", "Vec\t128" },
		{ "landModelFile", "String \"\"" },
		{ "landDefinitionFile", "String \"\"" },
		{ "landDimensions", "Vec\t128" },
		{ "landPageFile", "String \"\"" },
		{ "landDiffuseOnly", "Vec     0" },
		{ "landMappingModel", "String \"\"" },
		{ "landSourceModel", "String \"\"" },
		{ "landGenModel", "String \"\"" },
		{ "landShadowModel", "String \"\"" },
		{ "landLayoutVersion", "Vec 0" },
		{ "layoutDownscale", "Vec 1" },
		{ "landBorderWidth", "Vec\t4" },
		{ "altBumpContribution", "Vec\t0" },
		{ "altDiffuseContribution", "Vec\t0" },
		{ "altMaterial", "String \"\"" },
		{ "altScale", "Vec\t64" },
		{ "mrtNum", "Vec\t0" },
		{ "landStampBlendMode", "Vec 0" },
		{ "landStampBlendModeNone", "Vec 0" },
		{ "landStampBlendModeMultiply", "Vec 1" },
		{ "landStampBlendModeOverlay", "Vec 2" },
		{ "landStampBlendModeColorDodge", "Vec 3" },
		{ "landStampBlendModeColorBurn", "Vec 4" },
		{ "landStampBlendModeSoftLight", "Vec 5" },
		{ "landStampBlendModeColor", "Vec 6" },
		{ "landStampBlendModeDarken", "Vec 7" },
		{ "landStampBlendModeLighten", "Vec 8" },
		{ "landStampBlendModeSimpleBlend", "Vec 9" },
		{ "landStampBlendModeScreen", "Vec 10" },
		{ "landStampBlendModeLuminosity", "Vec 11" },
		{ "landEditBumpMap", "Tex\t_blockRenderTextureBump" },
		{ "landEditShadowMap", "Tex\t_blockRenderTextureShadow" },
		{ "landEditDiffuseMap", "Tex\t_blockRenderTextureDiffuse" },
		{ "landEditSpecularMap", "Tex\t_blockRenderTextureSpecular" },
		{ "landEditXYZMap", "Tex\t_blockRenderTextureXYZ" },
		{ "landEditRGBMap", "Tex\t_blockRenderTextureRGB" },
		{ "landShadowScale", "Vec\t{ 1.0 }" },
		{ "landTileFade", "Vec\t0.5" },
		{ "pageToTexelBlock", "Vec   0.46875" },
		{ "genCullBoundsMin", "Vec { -99999, -99999, -99999}" },
		{ "genCullBoundsMax", "Vec {  99999,  99999,  99999}" },
		{ "stampQueryST", "Vec 0" },
		{ "flareOriginNDC", "Vec { 0.0, 0.0, 0.0, 0.0 }" },
		{ "scanlineMap", "Tex\t_black" },
		{ "hologramColor", "Vec { 0, 0.4, 0.8, 0.6 }" },
		{ "modelFadeExtrude", "Vec 0.4" },
		{ "channelLight0", "Vec 0" },
		{ "channelLight1", "Vec 0" },
		{ "channelLight2", "Vec 0" },
		{ "channelLight3", "Vec 0" },
		{ "channelLight4", "Vec 0" },
		{ "channelLight5", "Vec 0" },
		{ "primeLightDir", "Vec 0" },
		{ "primeLightColor", "Vec 0" },
		{ "primeLightMin", "Vec 0.0" },
		{ "highlightColor", "Vec 0.0" },
		{ "particleLightDir", "Vec { 0.0, 1.0, 0.0, 0.0 }" },
		{ "particleLightCol", "Vec 1.0" },
		{ "particleFade", "Vec 0.009" },
		{ "depthClipRange", "Vec 0.001" },
		{ "burnPower", "Vec { 4, 1.0, 0.0, 0.0 }" },
		{ "burnColor", "Vec { 4, 4, 4, 1.0 }" },
		{ "burnMap", "Tex\t_black" },
		{ "slimeTileScroll", "Vec { 1.0, 1.0, 0.5, 0.5 }" },
		{ "addColor", "Vec { 0.0, 0.0, 0.0, 0.0 }" },
		{ "particleHologramColor", "Vec { 0.25, 0.45, 0.8, 0.6 }" },
		{ "feedbackColorMap", "TexMultisample2D\t_frontColor" },
		{ "sobelThreshold", "Vec 1.2" },
		{ "sobelOpacity", "Vec 1.0" },
		{ "showDepthOfField", "Vec 0 bool" },
		{ "depthOfField2", "Vec 0" },
		{ "radialBlurEnable", "Vec 0 bool" },
		{ "radialBlurCenter", "Vec { 0.5, 0.5, 0.0, 0.0 }" },
		{ "radialBlurScale", "Vec { 0.08, 0.5 }" },
		{ "radialBlurMaxScale", "Vec 0.5" },
		{ "radiosityPreviewX", "Vec 0" },
		{ "radiosityPreviewY", "Vec 0" },
		{ "radiosityPreviewZ", "Vec 0" },
		{ "radiosityPreviewW", "Vec 0" },
		{ "radiosityPreviewMap", "Tex\t_radiosityPreview" },
		{ "texDistortionScale", "Vec { 64.0 } range 1.0, 64.0" },
		{ "electricBoltTranslate", "Vec { 3, 0, 0, 10 }" },
		{ "electricBoltDistortScale", "Vec { 2, .5, .2, 1 }" },
		{ "distortionScale", "Vec 1.0" },
		{ "distortionFade", "Vec { 1, 4, 600, 700 }" },
		{ "distortionMap", "Tex _black" },
		{ "distortionMap1", "Tex _black" },
		{ "sfxLightDir", "Vec {0.57735, 0.57735, 0.57735}" },
		{ "sfxLightCol", "Vec 1.0" },
		{ "shieldBaseGridColor", "Vec\t{ 1, 1, 1, 1 }" },
		{ "shieldHexColor01", "Vec\t{ 1, 1, 1, 1 }" },
		{ "shieldHexColor02", "Vec\t{ 1, 1, 1, 1 }" },
		{ "shieldPatternTranslate", "Vec\t{ 1, 1, 1, 1 }" },
		{ "shieldSweepColor", "Vec\t{ 1, 1, 1, 1 }" },
		{ "envBlendMip", "Vec\t0" },
		{ "brightnessScale", "Vec 1.0" },
		{ "simpleShade_shadowAdd", "Vec 0.0" },
		{ "skyFogCutoffHeight", "Vec 0 range 0, 1000" },
		{ "skyScale", "Vec 1" },
		{ "skyColor", "Vec\t{ 1, 1, 1, 1 } color" },
		{ "cloudScale", "Vec 1" },
		{ "cloudScale1", "Vec 1" },
		{ "stencilPoint", "Vec\t1" },
		{ "stencilDir", "Vec\t1" },
		{ "vertexStScaleBias", "Vec { 1, 1, 0, 0 }" },
		{ "vertexXYZScale", "Vec { 1, 1, 1, 1 }" },
		{ "vertexXYZBias", "Vec { 0, 0, 0, 0 }" },
		{ "globalShadows", "Tex\t_globalShadowsImage" },
		{ "directLighting", "Tex\t_directLighting" },
		{ "_waveMap", "Tex _wave" },
		{ "fresnelMap", "Tex _fresnel" },
		{ "waterFresnel", "Vec { 0.0204, 0.9796, 0.0, 0.0 }" },
		{ "waveBumpScaleBias1", "Vec { 0.050, 0.050, -0.025, -0.002 }" },
		{ "waveBumpScaleBias2", "Vec { 0.070, 0.070,  0.030, -0.009 }" },
		{ "waveBumpScaleBias3", "Vec { 1, 1,  0.050, -0.010 }" },
		{ "waveBumpScaleBias4", "Vec { 0.095, 0.095,  0.040, -0.030 }" },
		{ "waterPowerMip", "Vec 2" },
		{ "waterFogColor", "Vec { 0.2, 0.43, 0.5, 0.0 }" },
		{ "waterFogScale", "Vec 0.0" },
		{ "waterFogNearColor", "Vec { 0.2, 0.43, 0.5, 0.0 }" },
		{ "waterFogFarColor", "Vec { 0.2, 0.43, 0.5, 0.0 }" },
		{ "waterAlphaScale", "Vec { 0.0, 1.0, 0.0, 0.0 }" },
		{ "foamHeight", "Vec 500" },
		{ "deepWaterColor", "Vec { 0.01, 0.01, 0.01, 0.4}" },
		{ "shallowWaterColor", "Vec { 0.025, 0.03, 0.04, 0.4 }" },
		{ "reflectionColor", "Vec 1" },
		{ "reflectionAmount", "Vec 0.8" },
		{ "waterAmount", "Vec 0.7" },
		{ "waterWaveDirX", "Vec 0" },
		{ "waterWaveDirY", "Vec 0" },
		{ "waterWaveFreq", "Vec 0" },
		{ "waterWaveAmp", "Vec 0" },
		{ "waterWavePhase", "Vec 0" },
		{ "waterHeight", "Vec\t0" },
		{ "sludgeColorBase", "Vec { 0.5, 0.5, 1, 1 }" },
		{ "sludgeMaskMap", "Tex\t_white" },
		{ "foamColor", "Vec { 0.5, 0.5, 1, 1 }" },
	};
}

void RegisterRecoveredCodeRenderParms() {
	static bool registered = false;
	if ( registered ) return;
	registered = true;
	for ( const recoveredCodeParmDef_t & definition : recoveredCodeParmDefs ) {
		new idCodeRenderParm( definition.name, definition.initializer );
	}
}

