#pragma once

#include "rendersystem.h"
#include "renderer_d3d9.h"
#include "../framework/rendermanager.h"
#include "../../shared/idlib/metrics/metrics.h"

class idDeclRenderParm;
class idDeclRenderProg;
class idDeclTable;
class idImage;
class idMaterial;
class idRenderDestination;
class idRenderThread;
class idRenderView;
class idRenderWorldLocal;
class idStaticModel;
class idTriangles;

struct performanceCounters_t {
	int c_modelCommits;
	int c_lightCommits;
	int c_modelReferences;
	int c_lightReferences;
	int c_viewWorldAreas;
	int c_viewModels;
	int c_viewLights;
	int c_viewShadows;
	int c_viewDimShadows;
	unsigned long long startGPUTimeMicroSec;
	unsigned long long endGPUTimeMicroSec;
	unsigned long long startLatchTimeMicroSec;
	unsigned long long endLatchTimeMicroSec;
	unsigned long long startCPUTimeMicroSec;
	unsigned long long endCPUTimeMicroSec;
	unsigned long long startSwapMicroSec;
	unsigned long long endSwapMicroSec;
};

class alignas( 16 ) idRenderSystemLocal : public idRenderSystem {
public:
	idRenderSystemLocal();
	~idRenderSystemLocal() override;
	void Init() override;
	void Init2() override;
	void Shutdown() override;
	idRenderWorld * AllocRenderWorld( const char *, bool ) override;
	void RenderFrame( void *, const idRenderFrameInfo *, bool, bool, bool ) override;
	void EndFrame( void *, int, int, idRenderWorld *, idRenderModel **, int,
		bool, bool, bool, int ) override;
	void ToolEndFrame( void *, int, int, idRenderWorld *, const renderView_t *,
		idRenderModel *, int ) override;
	int FrameNumber() override;
	bool SyncRenderThread( bool ) override;
	void BeginBinkVideo( void *, const char *, videoFlags_t, idRenderVideoOverlay * ) override;
	bool BinkVideoIsLoaded() override;
	bool BinkVideoIsPlaying() override;
	void FreeBinkVideo() override;
	void AllowBackgroundSwaps( bool ) override;
	void BeginAutomaticBackgroundSwaps( void *, bool ) override;
	void EndAutomaticBackgroundSwaps() override;
	void SetLoadingIconInfo( float, float, float, float ) override;
	void RegenerateReferences() override;
	void InhibitEndFrameRendering( int ) override;
	bool IsEndFrameRenderingInhibited() override;
	int GetNumRenderWorlds() override;
	idRenderWorld * RenderWorldForIndex( int ) override;
	int GetNextRenderView( idRenderWorld * ) override;
	int GetNumMonitors() override;
	void GetMonitorSize( int, int *, int * ) override;
	int GetCurrentMonitor() override;
	bool GPUTranscodeAvailable() override;
	void EnableGPUTranscode( bool ) override;
	bool GPUTranscodeIsEnabled() override;
	bool SwapTearAvailable() override;
	void ClearOutOfMemory() override;
	bool CheckOutOfMemory() override;
	void * GetGameWindow() override;
	void Restart() override;
	void SwapBuffers( void *, bool ) override;
	void SetBlackLevel( float ) override;
	void SetGamma( unsigned short *, unsigned short *, unsigned short * ) override;
	bool MakeCurrent( void * ) override;
	int GetWidth() override;
	int GetHeight() override;
	float GetPixelAspect() override;
	float GetScreenAspect() override;
	int GetScanoutWidth() override;
	int GetScanoutHeight() override;
	stereoRenderMode_t GetStereoRenderMode() override;
	int GetNumMultisamples() override;
	int GetMaxSupportedMultisamples() override;
	bool IgnoreSizeMessages() override;
	void WindowSizeDragged( int, int ) override;
	bool WindowChangeMultisamples( int ) override;
	bool EnumerateModes( int, int *, int *, int * ) override;
	void ( __fastcall * ExtensionPointer( const char * ) )() override;
	void SetPixelFormat( void * ) override;
	void ShowGameWindow() override;
	void HideGameWindow() override;
	bool IsFullscreen() override;
	void GoWindowed() override;
	void GoFullScreen() override;
	void SetStudioMode( bool ) override;
	void InitContext();
	void InitCommands();
	void InitUnitSquare();
	void InitRenderTextures();
	void StartRenderThread();
	void RestartRenderThread( void * window );
	bool WaitForNextVideoFrame();
	unsigned int GetBinkWidth() const;
	unsigned int GetBinkHeight() const;
	float GetBinkTime() const;
	void UpdateBinkTextures();
	bool ResetContext( int width, int height, bool fullscreen, int samples );
	void InitRenderTargets();
	void PurgeRenderTargets();

	bool insideEndFrame;
	bool automaticBackgroundSwapsEnabled;
	bool renderLoadingIcon;
	bool renderingIsReadyForSwapbuffers;
	bool allowBackgroundSwaps;
	volatile bool renderSynced;
	int frameCount;
	int inhibitRendering;
	float loadingIconPosX;
	float loadingIconPosY;
	float loadingIconScale;
	float loadingIconSpeed;
	idRenderWorldLocal * worlds;
	idRenderWorldLocal * primaryWorld;
	idRenderWorldLocal * performanceCounterLogWorld;
	int performanceCounterLogWorldFrame;
	idRenderWorldLocal * testWorld;
	idImage * testImage;
	idImage * testCubeImage;
	const idMaterial * testMaterial;
	performanceCounters_t pc;
	idRenderVideoOverlay * videoOverlay;
	const idMaterial * mtrDefault;
	const idDeclRenderProg * progDepthOnly;
	const idDeclRenderProg * progColorOnly;
	const idDeclRenderProg * progWireFrame;
	const idDeclRenderProg * progTextureOnly;
	const idDeclRenderProg * progCubeImageOnly;
	const idDeclRenderProg * progBasicBlend;
	const idDeclRenderProg * progOccluderDepthOnly;
	const idDeclRenderProg * progDeferredPointLight;
	const idDeclRenderProg * progDeferredSpotLight;
	const idDeclRenderProg * progDeferredParallelLight;
	const idDeclRenderProg * progGlobalFog;
	const idDeclRenderProg * progPostProcess;
	const idDeclRenderParm * rpFrameNumber;
	const idDeclRenderParm * rpViewColor;
	const idDeclTable * declHighlightTable;
	const idStaticModel * defaultCubeModel;
	idTriangles * unitSquareTris;
	idTriangles * unitCubeTris;
	idTriangles * zeroOneCubeTris;
	idTriangles * extrudeBoxTris;
	idImage * imgViewColor[2];
	idImage * imgViewDepth;
	idImage * imgColorGradingLUT[2];
	idImage * imgDistortion[2];
	idImage * imgGui;
	idImage * imgDynamicEnvironment[2];
	idRenderDestination * renderDestViewColor[2];
	idRenderDestination * renderDestViewDepth;
	idRenderDestination * renderDestDistortion[2];
	idRenderDestination * renderDestGui;
	idRenderDestination * renderDestDefault;
	int windowWidth;
	int windowHeight;
	int renderWidth;
	int renderHeight;
	idRenderFrameInfo currentRenderFrameInfo;
	idRenderView * currentRenderView;
	unsigned short gammaTable[256];
	float blackLevel[2];
	bool updateGammaTable;
	idGaugeMetric drawsMetric;
	idGaugeMetric trisMetric;
	idGaugeMetric vertsMetric;
	idRenderThread * renderThread;

	bool gpuTranscodeEnabled;
	bool outOfMemory;
	bool studioMode;
	bool binkLoaded;
	bool binkPlaying;
	int multisamples;
};

extern idRenderSystemLocal renderSystemLocal;
