#pragma once

enum aiMelee_t : int {
    AIMELEE_NONE = 1,
    AIMELEE_FORWARD = 2,
    AIMELEE_BACK = 4,
    AIMELEE_LEFT = 8,
    AIMELEE_RIGHT = 16,
    AIMELEE_KICK = 32,
    AIMELEE_PUNCH = 64,
    AIMELEE_MEDIUM = 128,
    AIMELEE_LONG = 256,
    AIMELEE_CROUCH_FORWARD = 512,
    AIMELEE_CROUCH_BACK = 1024,
    AIMELEE_CROUCH_LEFT = 2048,
    AIMELEE_CROUCH_RIGHT = 4096,
    AIMELEE_RAGE = 8192,
    AIMELEE_MOVING_FORWARD = 16384,
    AIMELEE_TAKEDOWN = 32768,
    AIMELEE_CROUCH_TYPES = 7680,
    AIMELEE_CLOSE = 96,
    AIMELEE_ALL = -1,
    AIMELEE_MAX = 16
};

enum aiAccuracy_t : int {
    ACCURACY_FROMSKILL = 0,
    ACCURACY_HORRIBLE = 1,
    ACCURACY_POOR = 2,
    ACCURACY_DECENT = 3,
    ACCURACY_GOOD = 4,
    ACCURACY_EXCELLENT = 5,
    ACCURACY_PERFECT = 6,
    ACCURACY_MAX = 7
};

enum aiSkill_t : int {
    AISKILL_INCOMPETENT = 0,
    AISKILL_EASY = 1,
    AISKILL_NORMAL = 2,
    AISKILL_HARD = 3,
    AISKILL_LETHAL = 4,
    AISKILL_MAX = 5
};

enum aiExtendedClipModelStatus_t : int {
    AIEXTENDEDCLIPMODELSTATUS_NONE = 0,
    AIEXTENDEDCLIPMODELSTATUS_HIPS = 1,
    AIEXTENDEDCLIPMODELSTATUS_MAX = 2
};

enum aiWalkModifier_t : int {
    AIWALKMOD_DEFAULT = 0,
    AIWALKMOD_ALT1 = 1,
    AIWALKMOD_ALT2 = 2,
    AIWALKMOD_GROUCHY = 3,
    AIWALKMOD_OLD = 4,
    AIWALKMOD_SLOW = 5,
    AIWALKMOD_ARMSCROSSED = 6,
    AIWALKMOD_MAX = 7
};

// Only the range used by this translation unit is named here. PDB evidence
// establishes the complete enum range as 0..115 with ANIMOVERRIDE_MAX 116.
enum overrideAnim_t : int {
    ANIMOVERRIDE_NONE = 0,
    ANIMOVERRIDE_DODGE_RIGHT = 2,
    ANIMOVERRIDE_DODGE_LEFT = 3,
    ANIMOVERRIDE_FLINCH_LEFT = 25,
    ANIMOVERRIDE_FLINCH_RIGHT = 26,
    ANIMOVERRIDE_MELEE_PUNCH = 34,
    ANIMOVERRIDE_MELEE_KICK = 35,
    ANIMOVERRIDE_MELEE_FORWARD = 36,
    ANIMOVERRIDE_MELEE_BACK = 37,
    ANIMOVERRIDE_MELEE_LEFT = 38,
    ANIMOVERRIDE_MELEE_RIGHT = 39,
    ANIMOVERRIDE_MELEE_CROUCHED_FORWARD = 40,
    ANIMOVERRIDE_MELEE_MEDIUM = 41,
    ANIMOVERRIDE_MELEE_LONG = 42,
    ANIMOVERRIDE_MELEE_MOVING_FORWARD = 43,
    ANIMOVERRIDE_MELEE_TAKEDOWN = 44,
    ANIMOVERRIDE_RAGE_ATTACK = 46,
    ANIMOVERRIDE_THROW_PROJECTILE = 47,
    ANIMOVERRIDE_CROUCHED_THROW_PROJECTILE = 48,
    ANIMOVERRIDE_MOVING_THROW_PROJECTILE = 49,
    ANIMOVERRIDE_SHOOT = 50,
    ANIMOVERRIDE_MAX = 116
};

overrideAnim_t AIMeleeTypeToOverrideAnim(aiMelee_t meleeType);

extern const char* const ACTIONSCRIPT_SELF_TARGET_NAME;
extern const char* const ACTIONSCRIPT_EXECUTOR_TARGET_NAME;
extern const char* const ACTIONSCRIPT_ACTIVATOR_TARGET_NAME;
extern const char* const ACTIONSCRIPT_PLAYER_NAME;
extern const int ACTIONSCRIPT_SELF_TARGET_NAME_LEN;
extern const int ACTIONSCRIPT_EXECUTOR_TARGET_NAME_LEN;
extern const int ACTIONSCRIPT_ACTIVATOR_TARGET_NAME_LEN;
extern const int ACTIONSCRIPT_PLAYER_NAME_LEN;
