#pragma once

#include "idlib/langdict.h"
#include "idlib/text/strstatic.h"

class idSWFScriptFunction;

// Dialog identifiers and types recovered from the retail executable.  Values
// are serialized/communicated by number, so their order is ABI data.
enum gameDialogMessages_t : int {
    GDM_INVALID = 0,
    GDM_SWAP_DISKS_TO1,
    GDM_SWAP_DISKS_TO2,
    GDM_SWAP_DISKS_TO3,
    GDM_NO_GAMER_PROFILE,
    GDM_PLAY_ONLINE_NO_PROFILE,
    GDM_LEADERBOARD_ONLINE_NO_PROFILE,
    GDM_NO_STORAGE_SELECTED,
    GDM_ONLINE_INCORRECT_PERMISSIONS,
    GDM_SP_QUIT_SAVE,
    GDM_SP_RESTART_SAVE,
    GDM_SP_SIGNIN_CHANGE,
    GDM_SERVER_NOT_AVAILABLE,
    GDM_CONNECTION_LOST_HOST,
    GDM_CONNECTION_LOST,
    GDM_OPPONENT_CONNECTION_LOST,
    GDM_HOST_CONNECTION_LOST,
    GDM_CONNECTION_TO_HOST_LOST,
    GDM_FAILED_TO_LOAD_RANKINGS,
    GDM_HOST_QUIT,
    GDM_BECAME_HOST_PARTY,
    GDM_NEW_HOST_PARTY,
    GDM_LOBBY_BECAME_HOST_GAME,
    GDM_LOBBY_NEW_HOST_GAME,
    GDM_NEW_HOST_GAME,
    GDM_NEW_HOST_GAME_STATS_DROPPED,
    GDM_BECAME_HOST_GAME,
    GDM_BECAME_HOST_GAME_STATS_DROPPED,
    GDM_LOBBY_DISBANDED,
    GDM_LEAVE_WITH_PARTY,
    GDM_LEAVE_LOBBY_RET_MAIN,
    GDM_LEAVE_LOBBY_RET_NEW_PARTY,
    GDM_MIGRATING,
    GDM_OPPONENT_LEFT,
    GDM_NO_MATCHES_FOUND,
    GDM_INVALID_INVITE,
    GDM_KICKED,
    GDM_BANNED,
    GDM_SAVING,
    GDM_OVERWRITE_SAVE,
    GDM_LOAD_REQUEST,
    GDM_AUTOSAVE_DISABLED_STORAGE_REMOVED,
    GDM_STORAGE_INVALID,
    GDM_STORAGE_REMOVED,
    GDM_CONNECTING,
    GDM_REFRESHING,
    GDM_DELETE_SAVE,
    GDM_DELETING,
    GDM_BINDING_ALREDY_SET,
    GDM_CANNOT_BIND,
    GDM_OVERLAY_DISABLED,
    GDM_DIRECT_MAP_CHANGE,
    GDM_DELETE_AUTOSAVE,
    GDM_QUICK_SAVE,
    GDM_MULTI_RETRY,
    GDM_MULTI_SELF_DESTRUCT,
    GDM_MULTI_VDM_QUIT,
    GDM_MULTI_COOP_QUIT,
    GDM_LOADING_PROFILE,
    GDM_STORAGE_REQUIRED,
    GDM_INSUFFICENT_STORAGE_SPACE,
    GDM_PARTNER_LEFT,
    GDM_RESTORE_CORRUPT_SAVEGAME,
    GDM_UNRECOVERABLE_SAVEGAME,
    GDM_PROFILE_SAVE_ERROR,
    GDM_LOBBY_FULL,
    GDM_QUIT_GAME,
    GDM_CONNECTION_PROBLEMS,
    GDM_VOICE_RESTRICTED,
    GDM_LOAD_DAMAGED_FILE,
    GDM_MUST_SIGNIN,
    GDM_CONNECTION_LOST_NO_LEADERBOARD,
    GDM_SP_SIGNIN_CHANGE_POST,
    GDM_MIGRATING_WAITING,
    GDM_MIGRATING_RELAUNCHING,
    GDM_MIGRATING_FAILED_CONNECTION,
    GDM_MIGRATING_FAILED_CONNECTION_STATS,
    GDM_MIGRATING_FAILED_DISBANDED,
    GDM_MIGRATING_FAILED_DISBANDED_STATS,
    GDM_MIGRATING_FAILED_PARTNER_LEFT,
    GDM_HOST_RETURNED_TO_LOBBY,
    GDM_HOST_RETURNED_TO_LOBBY_STATS_DROPPED,
    GDM_FAILED_JOIN_LOCAL_SESSION,
    GDM_DELETE_CORRUPT_SAVEGAME,
    GDM_LEAVE_INCOMPLETE_INSTANCE,
    GDM_UNBIND_CONFIRM,
    GDM_BINDINGS_RESTORE,
    GDM_NEW_HOST,
    GDM_CONFIRM_VIDEO_CHANGES,
    GDM_UNABLE_TO_USE_SELECTED_STORAGE_DEVICE,
    GDM_ERROR_LOADING_SAVEGAME,
    GDM_ERROR_SAVING_SAVEGAME,
    GDM_DISCARD_CHANGES,
    GDM_LEAVE_LOBBY,
    GDM_LEAVE_LOBBY_AND_TEAM,
    GDM_CONTROLLER_DISCONNECTED_0,
    GDM_CONTROLLER_DISCONNECTED_1,
    GDM_CONTROLLER_DISCONNECTED_2,
    GDM_CONTROLLER_DISCONNECTED_3,
    GDM_CONTROLLER_DISCONNECTED_4,
    GDM_CONTROLLER_DISCONNECTED_5,
    GDM_CONTROLLER_DISCONNECTED_6,
    GDM_DLC_ERROR_REMOVED,
    GDM_DLC_ERROR_CORRUPT,
    GDM_DLC_ERROR_MISSING,
    GDM_DLC_ERROR_MISSING_GENERIC,
    GDM_DISC_SWAP,
    GDM_NEEDS_INSTALL,
    GDM_NO_SAVEGAMES_AVAILABLE,
    GDM_ERROR_JOIN_TWO_PROFILES_ONE_BOX,
    GDM_WARNING_PLAYING_COOP_SOLO,
    GDM_MULTI_COOP_QUIT_LOSE_LEADERBOARDS,
    GDM_CORRUPT_CONTINUE,
    GDM_MULTI_VDM_QUIT_LOSE_LEADERBOARDS,
    GDM_WARNING_PLAYING_VDM_SOLO,
    GDM_NO_GUEST_SUPPORT,
    GDM_DISC_SWAP_CONFIRMATION,
    GDM_ERROR_LOADING_PROFILE,
    GDM_CANNOT_INVITE_LOBBY_FULL,
    GDM_WARNING_FOR_NEW_DEVICE_ABOUT_TO_LOSE_PROGRESS,
    GDM_DISCONNECTED,
    GDM_INCOMPATIBLE_NEWER_SAVE,
    GDM_ACHIEVEMENTS_DISABLED_DUE_TO_CHEATING,
    GDM_INCOMPATIBLE_POINTER_SIZE,
    GDM_TEXTUREDETAIL_RESTARTREQUIRED,
    GDM_TEXTUREDETAIL_INSUFFICIENT_CPU,
    GDM_CHECKPOINT_SAVE,
    GDM_CALCULATING_BENCHMARK,
    GDM_DISPLAY_BENCHMARK,
    GDM_DISPLAY_CHANGE_FAILED,
    GDM_GPU_TRANSCODE_FAILED,
    GDM_OUT_OF_MEMORY,
    GDM_CORRUPT_PROFILE,
    GDM_PROFILE_TOO_OUT_OF_DATE_DEVELOPMENT_ONLY,
    GDM_MAX
};

enum dialogType_t : int {
    DIALOG_INVALID = -1,
    DIALOG_ACCEPT = 0,
    DIALOG_CONTINUE,
    DIALOG_ACCEPT_CANCEL,
    DIALOG_YES_NO,
    DIALOG_CANCEL,
    DIALOG_WAIT,
    DIALOG_WAIT_BLACKOUT,
    DIALOG_WAIT_CANCEL,
    DIALOG_DYNAMIC,
    DIALOG_QUICK_SAVE,
    DIALOG_TIMER_ACCEPT_REVERT,
    DIALOG_CRAWL_SAVE,
    DIALOG_CONTINUE_LARGE,
    DIALOG_BENCHMARK
};

static_assert(GDM_MAX == 0x86, "Recovered dialog message values changed");
static_assert(DIALOG_BENCHMARK == 0x0D,
    "Recovered dialog type values changed");

struct idDialogInfo {
    idDialogInfo()
        : msg(GDM_INVALID), type(DIALOG_INVALID), acceptCB(nullptr),
          cancelCB(nullptr), altCBOne(nullptr), altCBTwo(nullptr),
          clear(false), waitClear(false), pause(false), forcePause(false),
          leaveOnClear(false), waitOnAtlas(false), renderDuringLoad(false),
          startTime(0), killTime(0), overrideMsg(), txt1(), txt2(), txt3(),
          txt4() {
    }

    gameDialogMessages_t msg;
    dialogType_t type;
    idSWFScriptFunction* acceptCB;
    idSWFScriptFunction* cancelCB;
    idSWFScriptFunction* altCBOne;
    idSWFScriptFunction* altCBTwo;
    bool clear;
    bool waitClear;
    bool pause;
    bool forcePause;
    bool leaveOnClear;
    bool waitOnAtlas;
    bool renderDuringLoad;
    int startTime;
    int killTime;
    idStrStatic<256> overrideMsg;
    idStrId txt1;
    idStrId txt2;
    idStrId txt3;
    idStrId txt4;
};

#if INTPTR_MAX == INT32_MAX
static_assert(sizeof(idDialogInfo) == 344,
    "Recovered idDialogInfo ABI changed");
#endif
