#pragma once

#include <cstdint>
#include <limits>

using byte = unsigned char;
using uint8 = std::uint8_t;
using uint16 = std::uint16_t;
using uint32 = std::uint32_t;
using uint64 = std::uint64_t;
using int8 = std::int8_t;
using int16 = std::int16_t;
using int32 = std::int32_t;
using int64 = std::int64_t;
using dword = std::uint32_t;
using ID_TIME_T = std::int64_t;
using interlockedInt_t = long;

// Recovered from the retail idTech 5 type information.  These values are
// part of the system/framework ABI (the retail list differs from BFG after
// the connection-loss entries), so keep every ordinal explicit.
enum gameDialogMessages_t : int32 {
	GDM_INVALID = 0x00,
	GDM_SWAP_DISKS_TO1 = 0x01,
	GDM_SWAP_DISKS_TO2 = 0x02,
	GDM_SWAP_DISKS_TO3 = 0x03,
	GDM_NO_GAMER_PROFILE = 0x04,
	GDM_PLAY_ONLINE_NO_PROFILE = 0x05,
	GDM_LEADERBOARD_ONLINE_NO_PROFILE = 0x06,
	GDM_NO_STORAGE_SELECTED = 0x07,
	GDM_ONLINE_INCORRECT_PERMISSIONS = 0x08,
	GDM_SP_QUIT_SAVE = 0x09,
	GDM_SP_RESTART_SAVE = 0x0A,
	GDM_SP_SIGNIN_CHANGE = 0x0B,
	GDM_SERVER_NOT_AVAILABLE = 0x0C,
	GDM_CONNECTION_LOST_HOST = 0x0D,
	GDM_CONNECTION_LOST = 0x0E,
	GDM_OPPONENT_CONNECTION_LOST = 0x0F,
	GDM_HOST_CONNECTION_LOST = 0x10,
	GDM_CONNECTION_TO_HOST_LOST = 0x11,
	GDM_FAILED_TO_LOAD_RANKINGS = 0x12,
	GDM_HOST_QUIT = 0x13,
	GDM_BECAME_HOST_PARTY = 0x14,
	GDM_NEW_HOST_PARTY = 0x15,
	GDM_LOBBY_BECAME_HOST_GAME = 0x16,
	GDM_LOBBY_NEW_HOST_GAME = 0x17,
	GDM_NEW_HOST_GAME = 0x18,
	GDM_NEW_HOST_GAME_STATS_DROPPED = 0x19,
	GDM_BECAME_HOST_GAME = 0x1A,
	GDM_BECAME_HOST_GAME_STATS_DROPPED = 0x1B,
	GDM_LOBBY_DISBANDED = 0x1C,
	GDM_LEAVE_WITH_PARTY = 0x1D,
	GDM_LEAVE_LOBBY_RET_MAIN = 0x1E,
	GDM_LEAVE_LOBBY_RET_NEW_PARTY = 0x1F,
	GDM_MIGRATING = 0x20,
	GDM_OPPONENT_LEFT = 0x21,
	GDM_NO_MATCHES_FOUND = 0x22,
	GDM_INVALID_INVITE = 0x23,
	GDM_KICKED = 0x24,
	GDM_BANNED = 0x25,
	GDM_SAVING = 0x26,
	GDM_OVERWRITE_SAVE = 0x27,
	GDM_LOAD_REQUEST = 0x28,
	GDM_AUTOSAVE_DISABLED_STORAGE_REMOVED = 0x29,
	GDM_STORAGE_INVALID = 0x2A,
	GDM_STORAGE_REMOVED = 0x2B,
	GDM_CONNECTING = 0x2C,
	GDM_REFRESHING = 0x2D,
	GDM_DELETE_SAVE = 0x2E,
	GDM_DELETING = 0x2F,
	GDM_BINDING_ALREDY_SET = 0x30,
	GDM_CANNOT_BIND = 0x31,
	GDM_OVERLAY_DISABLED = 0x32,
	GDM_DIRECT_MAP_CHANGE = 0x33,
	GDM_DELETE_AUTOSAVE = 0x34,
	GDM_QUICK_SAVE = 0x35,
	GDM_MULTI_RETRY = 0x36,
	GDM_MULTI_SELF_DESTRUCT = 0x37,
	GDM_MULTI_VDM_QUIT = 0x38,
	GDM_MULTI_COOP_QUIT = 0x39,
	GDM_LOADING_PROFILE = 0x3A,
	GDM_STORAGE_REQUIRED = 0x3B,
	GDM_INSUFFICENT_STORAGE_SPACE = 0x3C,
	GDM_PARTNER_LEFT = 0x3D,
	GDM_RESTORE_CORRUPT_SAVEGAME = 0x3E,
	GDM_UNRECOVERABLE_SAVEGAME = 0x3F,
	GDM_PROFILE_SAVE_ERROR = 0x40,
	GDM_LOBBY_FULL = 0x41,
	GDM_QUIT_GAME = 0x42,
	GDM_CONNECTION_PROBLEMS = 0x43,
	GDM_VOICE_RESTRICTED = 0x44,
	GDM_LOAD_DAMAGED_FILE = 0x45,
	GDM_MUST_SIGNIN = 0x46,
	GDM_CONNECTION_LOST_NO_LEADERBOARD = 0x47,
	GDM_SP_SIGNIN_CHANGE_POST = 0x48,
	GDM_MIGRATING_WAITING = 0x49,
	GDM_MIGRATING_RELAUNCHING = 0x4A,
	GDM_MIGRATING_FAILED_CONNECTION = 0x4B,
	GDM_MIGRATING_FAILED_CONNECTION_STATS = 0x4C,
	GDM_MIGRATING_FAILED_DISBANDED = 0x4D,
	GDM_MIGRATING_FAILED_DISBANDED_STATS = 0x4E,
	GDM_MIGRATING_FAILED_PARTNER_LEFT = 0x4F,
	GDM_HOST_RETURNED_TO_LOBBY = 0x50,
	GDM_HOST_RETURNED_TO_LOBBY_STATS_DROPPED = 0x51,
	GDM_FAILED_JOIN_LOCAL_SESSION = 0x52,
	GDM_DELETE_CORRUPT_SAVEGAME = 0x53,
	GDM_LEAVE_INCOMPLETE_INSTANCE = 0x54,
	GDM_UNBIND_CONFIRM = 0x55,
	GDM_BINDINGS_RESTORE = 0x56,
	GDM_NEW_HOST = 0x57,
	GDM_CONFIRM_VIDEO_CHANGES = 0x58,
	GDM_UNABLE_TO_USE_SELECTED_STORAGE_DEVICE = 0x59,
	GDM_ERROR_LOADING_SAVEGAME = 0x5A,
	GDM_ERROR_SAVING_SAVEGAME = 0x5B,
	GDM_DISCARD_CHANGES = 0x5C,
	GDM_LEAVE_LOBBY = 0x5D,
	GDM_LEAVE_LOBBY_AND_TEAM = 0x5E,
	GDM_CONTROLLER_DISCONNECTED_0 = 0x5F,
	GDM_CONTROLLER_DISCONNECTED_1 = 0x60,
	GDM_CONTROLLER_DISCONNECTED_2 = 0x61,
	GDM_CONTROLLER_DISCONNECTED_3 = 0x62,
	GDM_CONTROLLER_DISCONNECTED_4 = 0x63,
	GDM_CONTROLLER_DISCONNECTED_5 = 0x64,
	GDM_CONTROLLER_DISCONNECTED_6 = 0x65,
	GDM_DLC_ERROR_REMOVED = 0x66,
	GDM_DLC_ERROR_CORRUPT = 0x67,
	GDM_DLC_ERROR_MISSING = 0x68,
	GDM_DLC_ERROR_MISSING_GENERIC = 0x69,
	GDM_DISC_SWAP = 0x6A,
	GDM_NEEDS_INSTALL = 0x6B,
	GDM_NO_SAVEGAMES_AVAILABLE = 0x6C,
	GDM_ERROR_JOIN_TWO_PROFILES_ONE_BOX = 0x6D,
	GDM_WARNING_PLAYING_COOP_SOLO = 0x6E,
	GDM_MULTI_COOP_QUIT_LOSE_LEADERBOARDS = 0x6F,
	GDM_CORRUPT_CONTINUE = 0x70,
	GDM_MULTI_VDM_QUIT_LOSE_LEADERBOARDS = 0x71,
	GDM_WARNING_PLAYING_VDM_SOLO = 0x72,
	GDM_NO_GUEST_SUPPORT = 0x73,
	GDM_DISC_SWAP_CONFIRMATION = 0x74,
	GDM_ERROR_LOADING_PROFILE = 0x75,
	GDM_CANNOT_INVITE_LOBBY_FULL = 0x76,
	GDM_WARNING_FOR_NEW_DEVICE_ABOUT_TO_LOSE_PROGRESS = 0x77,
	GDM_DISCONNECTED = 0x78,
	GDM_INCOMPATIBLE_NEWER_SAVE = 0x79,
	GDM_ACHIEVEMENTS_DISABLED_DUE_TO_CHEATING = 0x7A,
	GDM_INCOMPATIBLE_POINTER_SIZE = 0x7B,
	GDM_TEXTUREDETAIL_RESTARTREQUIRED = 0x7C,
	GDM_TEXTUREDETAIL_INSUFFICIENT_CPU = 0x7D,
	GDM_CHECKPOINT_SAVE = 0x7E,
	GDM_CALCULATING_BENCHMARK = 0x7F,
	GDM_DISPLAY_BENCHMARK = 0x80,
	GDM_DISPLAY_CHANGE_FAILED = 0x81,
	GDM_GPU_TRANSCODE_FAILED = 0x82,
	GDM_OUT_OF_MEMORY = 0x83,
	GDM_CORRUPT_PROFILE = 0x84,
	GDM_PROFILE_TOO_OUT_OF_DATE_DEVELOPMENT_ONLY = 0x85,
	GDM_MAX = 0x86,

	// BFG used this older spelling for ordinal 0x11.
	GDM_HOST_CONNECTION_LOST_STATS = GDM_CONNECTION_TO_HOST_LOST
};

enum dialogType_t : int32 {
	DIALOG_INVALID = -1,
	DIALOG_ACCEPT = 0,
	DIALOG_CONTINUE = 1,
	DIALOG_ACCEPT_CANCEL = 2,
	DIALOG_YES_NO = 3,
	DIALOG_CANCEL = 4,
	DIALOG_WAIT = 5,
	DIALOG_WAIT_BLACKOUT = 6,
	DIALOG_WAIT_CANCEL = 7,
	DIALOG_DYNAMIC = 8,
	DIALOG_QUICK_SAVE = 9,
	DIALOG_TIMER_ACCEPT_REVERT = 10,
	DIALOG_CRAWL_SAVE = 11,
	DIALOG_CONTINUE_LARGE = 12,
	DIALOG_BENCHMARK = 13
};

enum saveGameType_t : int32 {
	SAVEGAMEFILE_NONE = 0x00,
	SAVEGAMEFILE_TEXT = 0x01,
	SAVEGAMEFILE_BINARY = 0x02,
	SAVEGAMEFILE_COMPRESSED = 0x04,
	SAVEGAMEFILE_PIPELINED = 0x08,
	SAVEGAMEFILE_THUMB = 0x10,
	SAVEGAMEFILE_BKGRND_IMAGE = 0x20,
	SAVEGAMEFILE_AUTO_DELETE = 0x40,
	SAVEGAMEFILE_OPTIONAL = 0x80
};

#ifndef ID_INLINE
#define ID_INLINE inline
#endif
#ifndef BIT
#define BIT( bit ) ( 1u << ( bit ) )
#endif
#ifndef BIT64
#define BIT64( bit ) ( 1ull << ( bit ) )
#endif
#ifndef compile_time_assert
#define compile_time_assert( expression ) static_assert( ( expression ), #expression )
#endif
#ifndef VERIFY_FORMAT_STRING
#define VERIFY_FORMAT_STRING
#endif
#ifndef MAX_STRING_CHARS
#define MAX_STRING_CHARS 1024
#endif
#ifndef MAX_OSPATH
#define MAX_OSPATH 256
#endif
#ifndef S_COLOR_DEFAULT
#define S_COLOR_DEFAULT "^0"
#define S_COLOR_RED "^1"
#define S_COLOR_GREEN "^2"
#define S_COLOR_YELLOW "^3"
#endif

// Category bits used by the original idTech 5 cvar declarations.  The
// recovered shared cvar facade currently exposes only value/behavior bits.
#ifndef CVAR_SYSTEM
#define CVAR_SYSTEM 0x00000008
#endif
#ifndef CVAR_RENDERER
#define CVAR_RENDERER 0x00000010
#endif
#ifndef CVAR_SOUND
#define CVAR_SOUND 0x00000020
#endif
#ifndef CVAR_GUI
#define CVAR_GUI 0x00000040
#endif
#ifndef CVAR_GAME
#define CVAR_GAME 0x00000080
#endif
#ifndef CVAR_TOOL
#define CVAR_TOOL 0x00000100
#endif
#ifndef CVAR_SERVERINFO
#define CVAR_SERVERINFO 0x00000400
#endif
#ifndef CVAR_NETWORKSYNC
#define CVAR_NETWORKSYNC 0x00000800
#endif

#ifndef MAX_TYPE
#define MAX_TYPE( type ) ( (std::numeric_limits< type >::max)() )
#endif

#ifndef MAX_UNSIGNED_TYPE
#define MAX_UNSIGNED_TYPE( type ) ( (std::numeric_limits< type >::max)() )
#endif

#ifndef ALIGNTYPE16
#if defined( _MSC_VER )
#define ALIGNTYPE16 __declspec( align( 16 ) )
#else
#define ALIGNTYPE16 alignas( 16 )
#endif
#endif
